import random
quotes = ["Don't cry because it's over, smile because it happened. - Dr. Seuss",
"Don't cry because it's over, smile because it happened. - Dr. Seuss",
"I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best. - Marilyn Monroe",
"I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best. - Marilyn Monroe",
"I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best. - Marilyn Monroe",
"Be yourself; everyone else is already taken. - Oscar Wilde",
"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
"Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind. - Bernard M. Baruch",
"You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth. - William W. Purkey",
"You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth. - William W. Purkey",
"You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth. - William W. Purkey",
"You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
"A room without books is like a body without a soul. - Marcus Tullius Cicero",
"A room without books is like a body without a soul. - Marcus Tullius Cicero",
"So many books, so little time. - Frank Zappa",
"So many books, so little time. - Frank Zappa",
"You only live once, but if you do it right, once is enough. - Mae West",
"You only live once, but if you do it right, once is enough. - Mae West",
"Be the change that you wish to see in the world. - Mahatma Gandhi",
"Be the change that you wish to see in the world. - Mahatma Gandhi",
"In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
"Friendship ... is born at the moment when one man says to another What! You too? I thought that no one but myself . . . - C.S. Lewis,  The Four Loves",
"If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals. - J.K. Rowling,  Harry Potter and the Goblet of Fire",
"Don't walk in front of me I may not followDon't walk behind me I may not leadWalk beside me just be my friend - Albert Camus",
"No one can make you feel inferior without your consent. - Eleanor Roosevelt,  This is My Story",
"No one can make you feel inferior without your consent. - Eleanor Roosevelt,  This is My Story",
"If you tell the truth, you don't have to remember anything. - Mark Twain",
"A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
"A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
"Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
"I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
"Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
"Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
"I am so clever that sometimes I don't understand a single word of what I am saying. - Oscar Wilde,  The Happy Prince and Other Stories",
"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.,  A Testament of Hope: The Essential Writings and Speeches",
"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.,  A Testament of Hope: The Essential Writings and Speeches",
"To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
"Without music, life would be a mistake. - Friedrich Nietzsche,  Twilight of the Idols",
"Without music, life would be a mistake. - Friedrich Nietzsche,  Twilight of the Idols",
"Insanity is doing the same thing, over and over again, but expecting different results. - Narcotics Anonymous",
"Insanity is doing the same thing, over and over again, but expecting different results. - Narcotics Anonymous",
"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
"I believe that everything happens for a reason. People change so that you can learn to let go, things go wrong so that you appreciate them when they're right, you believe lies so you eventually learn to trust no one but yourself, and sometimes good things fall apart so better things can fall together. - Marilyn Monroe",
"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover. - H. Jackson Brown Jr.,  P.S. I Love You",
"We accept the love we think we deserve. - Stephen Chbosky,  The Perks of Being a Wallflower",
"We accept the love we think we deserve. - Stephen Chbosky,  The Perks of Being a Wallflower",
"It is better to be hated for what you are than to be loved for what you are not. - Andr� Gide,  Autumn Leaves",
"It is better to be hated for what you are than to be loved for what you are not. - Andr� Gide,  Autumn Leaves",
"Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe",
"All that is gold does not glitter,Not all those who wander are lost;The old that is strong does not wither,Deep roots are not reached by the frost.From the ashes a fire shall be woken,A light from the shadows shall spring;Renewed shall be blade that was broken,The crownless again shall be king. - J.R.R. Tolkien,  The Fellowship of the Ring",
"The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. - Jane Austen,  Northanger Abbey",
"The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. - Jane Austen,  Northanger Abbey",
"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
"It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it. - Maurice Switzer",
"As he read, I fell in love the way you fall asleep: slowly, and then all at once. - John Green,  The Fault in Our Stars",
"It is our choices, Harry, that show what we truly are, far more than our abilities. - J.K. Rowling,  Harry Potter and the Chamber of Secrets",
"Life is what happens to you while you're busy making other plans. - Allen Saunders",
"Good friends, good books, and a sleepy conscience: this is the ideal life. - Mark Twain",
"Good friends, good books, and a sleepy conscience: this is the ideal life. - Mark Twain",
"Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect). - Mark Twain",
"It does not do to dwell on dreams and forget to live. - J.K. Rowling,  Harry Potter and the Sorcerer's Stone",
"The fool doth think he is wise, but the wise man knows himself to be a fool. - William Shakespeare,  As You Like It",
"A woman is like a tea bag; you never know how strong it is until it's in hot water. - Eleanor Roosevelt",
"Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bil Keane",
"Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bil Keane",
"We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde,  Lady Windermere's Fan",
"If you don't stand for something you will fall for anything. - Gordon A. Eadie",
"The man who does not read has no advantage over the man who cannot read. - Mark Twain",
"I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
"It is not a lack of love, but a lack of friendship that makes unhappy marriages. - Friedrich Nietzsche",
"It is not a lack of love, but a lack of friendship that makes unhappy marriages. - Friedrich Nietzsche",
"The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. - Elie Wiesel",
"The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. - Elie Wiesel",
"The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference. - Elie Wiesel",
"Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. - Neil Gaiman,  Coraline",
"Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. - Neil Gaiman,  Coraline",
"Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read. - Groucho Marx,  The Essential Groucho: Writings For By And About Groucho Marx",
"Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read. - Groucho Marx,  The Essential Groucho: Writings For By And About Groucho Marx",
"I may not have gone where I intended to go, but I think I have ended up where I needed to be. - Douglas Adams,  The Long Dark Tea-Time of the Soul",
"I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. - Albert Einstein",
"A day without sunshine is like, you know, night. - Steve Martin",
"I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living. - Dr. Seuss",
"Never put off till tomorrow what may be done day after tomorrow just as well. - Mark Twain",
"I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close. - Pablo Neruda,  100 Love Sonnets",
"I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close. - Pablo Neruda,  100 Love Sonnets",
"I solemnly swear that I am up to no good. - J.K. Rowling,  Harry Potter and the Prisoner of Azkaban",
"That which does not kill us makes us stronger. - Friedrich Nietzsche",
"Have you ever been in love? Horrible isn't it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up. - Neil Gaiman,  The Sandman, Vol. 9: The Kindly Ones",
"Love all, trust a few, do wrong to none. - William Shakespeare,  All's Well That Ends Well",
"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go... - Dr. Seuss,  Oh, The Places You'll Go!",
"If you judge people, you have no time to love them. - Mother Teresa",
"There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment. - Sarah Dessen,  The Truth About Forever",
"For every minute you are angry you lose sixty seconds of happiness. - Ralph Waldo Emerson",
"Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. - Lao Tzu",
"My thoughts are stars I cannot fathom into constellations. - John Green,  The Fault in Our Stars",
"I love deadlines. I love the whooshing noise they make as they go by. - Douglas Adams,  The Salmon of Doubt",
"I love deadlines. I love the whooshing noise they make as they go by. - Douglas Adams,  The Salmon of Doubt",
]

def print_random_quote():
    print(quotes[random.randint(0,99)])